---
title: "FAIRness of COVID-19 medical data"
author:
  - Eero Raittio^[Institute of Dentistry, University of Eastern Finland, Kuopio, Finland.; eero.raittio@uef.fi]
  - Ahmad Sofi-Mahmudi^[Seqiz Health Network, Kurdistan University of Medical Sciences, Seqiz, Iran.; a.sofimahmudi@gmail.com]
  - Sergio E. Uribe*^[Department of Conservative Dentistry and Oral Health & Bioinformatics Research Unit, Riga Stradins University, Riga, Latvia.; sergio.uribe@rsu.lv] ^[School of Dentistry, Universidad Austral de Chile, Valdivia, Chile]
format: html
editor: visual
bibliography: references.bib
csl: vancouver.csl
---

**Corresponding author:** Sergio E. Uribe; Address: ; Telephone: ; Email: .

**Authors' contributions:** All authors conceived and designed, and wrote and revised the protocol.

# Abstract

**Objective and aim:** Access to research data increases confidence in research results by other researchers, the public, and policy and decision makers. A data management and dissemination framework was developed with guidelines to make data findable, accessible, interoperable and reusable, the FAIR principles[@Wilkinson2016-bo]. Our aim is to evaluate the amount of data available from COVID19 research and to assess compliance with the FAIR principles.

**Methods:** Descriptive study. We adhere to the recommendations for reporting STROBE descriptive studies[@Von_Elm2007-th]. We will search for all articles about COVID19 available in the EuroPMC database published between January 2020 and December 2021. We will extract information from available research data, either as supplementary material to the publication or available in an external repository. We will then evaluate the FAIR metrics of each repository using the tool F-UJI - An Automated FAIR Data Assessment Tool[@Devaraju_undated-ex].

**Discussion:** We hope to obtain an estimate of the availability of research data associated with COVI19 publications and adherence to FAIR principles. We hope that this information will contribute to the discussion about what measures can be taken to improve the confidence of the public and policy makers in the results of scientific research.

***Keywords:*** FAIR principles, Research data, Data Repositories, Research Methods, Open data, Open research

# Aims

To evaluate the amount of data available from COVID19 research and to assess compliance with the FAIR principles

# Methods

## Data sources and study selection

We will search for open access COVID-19-related articles from medical journals available in the Europe PMC database. We will restrict our search to papers in English. We will consider papers published from 2020-01-01 to 2021-12-31 with variants of COVID-19 keyword in their title, keywords, or results. We will download all identified records in XML full-text format (for full-text evaluation) and in CSV format (for descriptive tabulations) from the database. The search query will be as follows:

(COVID-19 query for title, keywords, and results) AND (SRC:"MED") AND (LANG:"eng" OR LANG:"en" OR LANG:"us") AND (FIRST_PDATE:\[2020-01-01 TO 2021-12-31\]) AND ((IN_EPMC:y) OR (OPEN_ACCESS:y)) AND (PUB_TYPE:"Journal Article" OR PUB_TYPE:"research-article" OR PUB_TYPE:"rapid-communication" OR PUB_TYPE:"product-review")'

The COVID-19 query is available in the *covid_keywords.csv* file.

<<<<<<< HEAD
## Data analysis

Then, COVI19 research data shared via the repositories will be analyzed to verify compliance with FAIR principles using the FAIRsFAIR Data Object Assessment Metrics[@Devaraju2020-yu].

We will perform descriptive analyses to generate tables and graphs to evaluate compliance with FAIR principles. Additionally, we will perform sub-analyses to detect differences between journals, research areas and time periods.

# Limitations
=======
## Data extraction and synthesis

First, from all those articles, we will identify articles which shared data. 

To do so, we will use a validated and automated tool developed by Serghiou et al. [@serghiou2021] to detect studies that shared data from open access articles downloaded from the Europe PMC database. Then, we will manually confirm that articles actually shared their data and then extract link or DOI to the data.

Then adherence of shared data to FAIR-principles will be evaluated using automated and validated F-UJI tool.

Basic journal- and article-related information (publisher, publication year and journal name) will be retrieved from the Europe PMC database. We will download additional information about journal impact factors from the Journal Citation Reports.
>>>>>>> 9add9417b2582281013963cac7a1598cdca3a99e

The study sample will be restricted to open access articles in the Europe PMC database which may not correspond to all COVID-19-related studies published in medical journals. However, as the majority of COVID-19-related papers are open access, hence we hope to obtain an estimation of the quality of the available data on COVID19.

## Funding

SUE acknowledges financial support from the European Union's Horizon 2020 research and innovation programme under grant agreement No 857287 and the Uzņēmuma MikroTik līgumam Nr. UL8, 2021 RSU.

\

# Referencesd
